### ISSUE TITLE
Unknown connection status

### ISSUE THREAD

**Issue by Sphinx2k** [bekriebel/fvtt-module-avclient-livekit#67] opened 2024-05-01 07:25 UTC
Hello, I have a problem that is now occurring for the second time. I am using the current Foundry version V11 315 and the module is also up to date, 
Some time ago a player was not sending video, he could still see others.  The dot (green, yellow, red) was white and it said "Unknown connection Quality". I then restarted the Lifekit container, FoundryVtt and the whole server and nothing changed. The "Reset meeting room ID" in the client settings did also not work. 
Then I logged in with his user on my PC and had the same problem. 
On the player PC i logged in another user, video worked. So I deleted his user profile and created a new one and the problem was solved. 
Yesterday it occurred again, this time affecting 3 players. I can probably help this time too by recreating them and reassigning all permissions. But I think there must be an explanation and a better solution. It feels like they are blacklisted from sending or something like this.

I can't find any error message in the console output.

**Comment by Sphinx2k** [comment] 2024-05-01 07:44
Meybe it was me?
I bevor this happend i accidently hit the "disable receiving video" button instead of disabling my camera. 
This is btw. how it looks.
![foundryvideoerror](https://github.com/bekriebel/fvtt-module-avclient-livekit/assets/6334267/4a7b7790-15c7-4c56-b891-bad6a23a2b02)

And If i click the "enable user video" button. I get this error: "You cannot enable the user's camera because they have hidden themselves."

**Comment by bekriebel** [comment] 2024-05-01 17:13
If it is saying they have hidden themselves, that is indicating that they have their video muted or disabled on their end.

If you are running your own LiveKit server, I recommend updating to the latest version. There is a bug on Chrome based browsers that is preventing video from working in some cases. The latest version of the LiveKit server works around this.

**Comment by Sphinx2k** [comment] 2024-05-01 18:13
I can report they have not disabled there video on there end.
But on your Post i testet it with two Firefox instances instead of one Chrome and one Firefox. With the two FF instances everything worked. So i will have to figure out how to update the livekit server -,-

Is there a better tutorial for the Lifekit Part somewhere for linux? I took me hours to get it working in the end. And the tutorials on the offical site are still not good in my opinion.

**Comment by jacksands** [comment] 2024-05-01 19:33
Hi!  I'm using the free tier of the livekit on https://livekit.io/   and I'm also experiencing the same error, so I don't think it is a server issue, that happens with multiple players, the error was observed using  Edge,  Chrome, opera and firefox (all on player side with foundry app local as server).

I can confirm no one hided or disable their cameras because they can see themselves and have checked that possibility.

I teste with version v0.5.26, v0.5.27, v0.5.28...  and 7 seems to suffer less form that bug

all on foundry v 11  315

In any case thanks for your module, fisrt time I experience any problems

**Comment by bekriebel** [comment] 2024-05-01 21:33
@jacksands I just tried with a quick livekit.io instance and my initial tests seemed to work well. Make sure you are also running the latest version of the module, as the newer versions of LiveKit also need updated client code.

@Sphinx2k It looks like if you turn on trace logging, the livekit server does output its version
![image](https://github.com/bekriebel/fvtt-module-avclient-livekit/assets/183779/a8701056-abfb-48ea-bc6b-82d499641027)

It looks like livekit.io is on version 1.6.0, which should be fine with the latest client version. Depending on when @jacksands last tested it, it's possible they were still on a version that didn't have the codec fixes, though.

**Comment by jacksands** [comment] 2024-05-01 21:48
Thank you!!!

I will test it as soon as I can

**Comment by jacksands** [comment] 2024-05-03 11:23
teste with version v0.5.29 and it worked without problems!!!

thank you for the assistance!

**Comment by bekriebel** [comment] 2024-05-03 16:38
Sounds good! Since it sounds like both of you have found a solution, I'll go ahead and close this issue.

**Closed by bekriebel** 2024-05-03 16:38 UTC
